stages:
  - dockerize
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  BRANCH: $CI_COMMIT_REF_NAME

dockerize:
  image: docker:latest
  stage: dockerize
  services:
    - docker:dind
  script:
    - docker build --build-arg STAGE=$BRANCH -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - development
    - master

deploy-development:
  image: alpine:latest
  stage: deploy
  tags:
    - gitlab-org
  script:
    - apk update && apk add openssh-client
    - chmod og= $ID_RSA

    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f tac-web || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8002:80 --name tac-web $TAG_COMMIT"
  only:
    - development

deploy-production:
  image: alpine:latest
  stage: deploy
  tags:
    - gitlab-org
  script:
    - chmod og= $ID_RSA_PROD
    - apk update && apk add openssh-client

    - ssh -i $ID_RSA_PROD -o StrictHostKeyChecking=no $SERVER_USER_PROD@$SERVER_IP_PROD "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA_PROD -o StrictHostKeyChecking=no $SERVER_USER_PROD@$SERVER_IP_PROD "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA_PROD -o StrictHostKeyChecking=no $SERVER_USER_PROD@$SERVER_IP_PROD "docker container rm -f tac-api || true"
    - ssh -i $ID_RSA_PROD -o StrictHostKeyChecking=no $SERVER_USER_PROD@$SERVER_IP_PROD "docker run --env-file $ENV_PROD -d -p 8002:3000 --name tac-api $TAG_COMMIT"
  only:
    - master
